version: '2'
services:
  web:
    environment:
      SITE_ENVIRONMENT: "docker"
    container_name: myaccount
    build: conf/web
    expose:
      - "80"
      - "443"
      - "9099"
      - "8084"
      - "8085"
      - "8086"
    ports:
      - "80:80"
      - "9099:9099"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
    volumes:
      - .:/srv/myaccount
    tty: true
